# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-12 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('map_app', '0003_auto_20171007_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usertokens',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usertokens',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='usertokens',
            name='authorized_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='usertokens',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usertokens',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
