# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-29 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_auto_20171012_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokens',
            name='authorized_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
