# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-29 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0005_auto_20171029_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokens',
            name='authorized_url',
            field=models.URLField(max_length=700, null=True),
        ),
    ]
